"""
应用常量定义
集中管理所有硬编码值，便于维护和配置
"""

# 数据单位转换
BYTES_TO_MB = 1000.0 * 1000.0  # 字节转MB
MB_TO_GB = 1.0  # MB转GB（已经在上面转换）
GB_TO_TB = 1024.0  # GB转TB

# 业务限制
MAX_CELL_QUERY_LIMIT = 200  # 单次查询最大小区数量
DEFAULT_PAGE_SIZE = 20  # 默认分页大小
TOP_CELLS_DEFAULT_LIMIT = 50  # Top小区默认数量
TOP_CELLS_EXPORT_LIMIT = 200  # Top小区导出数量

# 时间粒度
GRANULARITY_15MIN = "15m"
GRANULARITY_1HOUR = "1h"
GRANULARITY_1DAY = "1d"
VALID_GRANULARITIES = [GRANULARITY_15MIN, GRANULARITY_1HOUR, GRANULARITY_1DAY]

# 网络类型
NETWORK_4G = "4G"
NETWORK_5G = "5G"
VALID_NETWORKS = [NETWORK_4G, NETWORK_5G]

# 时间范围
TIME_RANGE_6H = "6h"
TIME_RANGE_12H = "12h"
TIME_RANGE_24H = "24h"
VALID_TIME_RANGES = [TIME_RANGE_6H, TIME_RANGE_12H, TIME_RANGE_24H]

# 默认阈值
DEFAULT_THRESHOLD_4G = 50.0
DEFAULT_THRESHOLD_5G = 50.0

# 缓存TTL（秒）
CACHE_TTL_1MIN = 60
CACHE_TTL_5MIN = 300

# 数据库表名
TABLE_4G_15MIN = "cell_4g_metrics"
TABLE_4G_1HOUR = "cell_4g_metrics_hour"
TABLE_5G_15MIN = "cell_5g_metrics"
TABLE_5G_1HOUR = "cell_5g_metrics_hour"

# Excel样式配置
EXCEL_HEADER_COLOR = "366092"
EXCEL_HEADER_FONT_COLOR = "FFFFFF"
EXCEL_HEADER_FONT_SIZE = 12

# 自动刷新配置
DEFAULT_AUTO_REFRESH_INTERVAL = 300  # 秒

# 日期格式
DATETIME_FORMAT = "%Y-%m-%dT%H:%M"
DATE_FORMAT = "%Y-%m-%d"
FILENAME_DATETIME_FORMAT = "%Y%m%d_%H%M"

# 性能监控阈值（毫秒）
PERF_THRESHOLD_ERROR = 2000  # 超过2秒记录为ERROR
PERF_THRESHOLD_WARNING = 1000  # 超过1秒记录为WARNING
PERF_THRESHOLD_INFO = 500  # 超过500ms记录为INFO
